sudo: false
language: node_js
node_js:
  - "8"
  - "6"

script: npm run test-ci
before_install:
- npm install -g npm@5
- npm install -g --production greenkeeper-lockfile@1 coveralls
before_script: greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- cat ./coverage/lcov.info | coveralls
